version: '3.4'
services:
  ui:
    build:
      context: .
      target: base
    container_name: expenses_ui
    image: expenses_ui
    command: npm start
    ports:
    - '3000:3000'
    volumes:
    - ${PWD}:/usr/src/app
    - /usr/src/app/node_modules
