version: '3.4'
services:
  ui:
    build:
      context: .
      target: base
    container_name: expenses_dev
    image: expenses_dev
    command: npm start
    ports:
    - '5000:3000'
    volumes:
    - ${PWD}:/usr/src/app
    - /usr/src/app/node_modules
    
  # prod:
  #   build:
  #     context: .
  #     target: production
  #   container_name: expenses_prod
  #   image: expenses_prod
  #   command: npm run prod
  #   ports:
  #   - '3000:3000'
  #   volumes:
  #   - ${PWD}:/usr/src/app
  #   - /usr/src/app/node_modules

