version: '3'
services:
  ui:
    build: .
    container_name: expenses-ui
    image: expenses_ui
    command: npm start
    ports:
    - '3000:3000'
    volumes:
    - ${PWD}:/usr/src/app
    - /usr/src/app/node_modules
