version: '3'
services:
  ui:
    build:
      context: .
      target: production
    container_name: expenses_ui
    image: expenses_ui
    command: npm start
    ports:
    - '3000:3000'
    volumes:
    - .:/usr/src/app
     - /usr/src/app/node_modules
